---
elasticsearch_cluster_name: wazuh
elasticsearch_node_name: node-1
elasticsearch_http_port: 9200
elasticsearch_network_host: 127.0.0.1
elasticsearch_jvm_xms: null
elastic_stack_version: 7.2.0
single_node: false
elasticsearch_bootstrap_node: false
elasticsearch_master_candidate: false
elasticsearch_cluster_nodes:
  - 127.0.0.1
elasticsearch_discovery_nodes:
  - 127.0.0.1

# X-Pack Security 
elasticsearch_xpack_security: false
elasticsearch_xpack_security_user: elastic
elasticsearch_xpack_security_password: elastic_pass

node_certs_generator: false
node_certs_generator_ip: 172.16.0.161
node_certs_source: /usr/share/elasticsearch
node_certs_destination: /etc/elasticsearch/certs

master_certs_destination: /es_certs


# Following parameters configure the elasticsearch-certutil binary execution.
# Visit https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html for more information

# The master_certs_destination is the folder which will contains the certificates and will be used for certs distribution

# CA generation 
generate_CA: false         
pkcs12_file_name: ""                     # Specifies the path to an existing CA key pair (in PKCS#12 format).
pkcs12_ca_pass: ""                       # Specifies the password for an existing CA private key or the generated CA private key.
generated_certs_keys_pass: ""            # Specifies the password for the generated private keys. Required in PKCS12, optional in PEM.
pem_key_name: myCA.key                   # Specifies the path to an existing CA private key (in PEM format)
pem_cert_name: myCA.pem                  # Specifies the path to an existing CA certificate (in PEM format)

# Rsync
rsync_path: /usr/bin/rsync
rsync_user: vagrant
rsync_extra_parameters: -avg -e 'ssh -o StrictHostKeyChecking=no' --rsync-path='sudo rsync'





