---
kibana_node_name: node-1

elasticsearch_http_port: "9200"
elasticsearch_network_host: "127.0.0.1"
kibana_server_host: "0.0.0.0"
kibana_server_port: "5601"
elastic_stack_version: 7.5.1
wazuh_version: 3.11.0
wazuh_app_url: https://packages.wazuh.com/wazuhapp/wazuhapp

# Xpack Security
kibana_xpack_security: false

elasticsearch_xpack_security_user: elastic
elasticsearch_xpack_security_password: elastic_pass

node_certs_generator: false
node_certs_source: /usr/share/elasticsearch
node_certs_destination: /etc/kibana/certs

# CA Generation
master_certs_path: /es_certs
generate_CA: true
ca_cert_name: ""

# Nodejs
nodejs:
  repo_dict:
      debian: "deb"
      redhat: "rpm"
  repo_url_ext: "nodesource.com/setup_8.x" 

# Build from sources
build_from_sources: false
wazuh_plugin_branch: 3.10-7.4